language: elixir

elixir: 1.3.2

otp_release:
  - 18.3
  - 19.0

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - clang

env:
  - MIX_ENV=test

before_script:
  - mix deps.get --only test
  - make

script:
  - mix coveralls.travis
