language: elixir

notifications:
  email: false

elixir: 1.3.2

otp_release:
  - 19.0

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - debian-sid
    packages:
      - gcc-4.9
      - lcov
      - libblas-dev
      - libgsl0-dev

env:
  - MIX_ENV=test

before_script:
  - mix deps.get --only test
  - mix dialyzer.plt
  - CC=gcc-4.9 make

script:
  - make test
  - mix coveralls.travis
  - mix dialyzer
