notifications:
  email: false

sudo: required

services:
  - docker

before_script:
  - docker build -t exlearn --build-arg HOST_USER_UID=`id -u` --build-arg HOST_USER_GID=`id -g` -f docker/project/Dockerfile "$PWD"

script:
  - docker run --rm -it -e COVERALLS_REPO_TOKEN -e COVERALLS_SERVICE_NAME -u `id -u`:`id -g` -v "$PWD":/work -w /work exlearn bash -c "mix deps.get && mix dialyzer.plt && make && make test && mix coveralls.travis && mix dialyzer --halt-exit-status"
